### ISSUE TITLE
Pytorch IoU as evaluation metric

### ISSUE THREAD

**Issue by kulkarnikeerti** [qhanghu/HSSN_pytorch#11]
Hi @qhanghu, @lingorX

Can I use PyTorch's `jaccard_index` to calculate `IoU's` instead of calculating it with code? As per my understanding this calculation does exactly what `jaccar_index` is doing. Or did I miss something and misunderstood the functionality here?

https://github.com/qhanghu/HSSN_pytorch/blob/c2386b758abda6dcfd86b572fe84b0527a6bc9e2/mmseg/core/evaluation/metrics.py#L5

**Comment by lingorX** [comment]
Hi, 

Yes, you can. But I do not recommend modifying the source code of mmseg since it is highly organized and may cause unexpected errors.
