### ISSUE TITLE
multi-scale testing shows poor performance

### ISSUE THREAD

**Issue by jhyukjang** [qhanghu/HSSN_pytorch#12]
# multi-gpu, multi-scale testing
tools/dist_test.sh <CONFIG_FILE> <SEG_CHECKPOINT_FILE> <GPU_NUM> --aug-test --eval mIoU

I run this shell script with Pascal-Person-Part dataset, but got poor results.
Could you solve the problem?

**Comment by lingorX** [comment]
Hi,

Could you provide more details? For example, the printed results.

**Comment by jhyukjang** [comment]
For Pascal-Person-Part dataset, single-gpu testing shows exact results as you report, but multi-gpu multu-scale testing with command

tools/dist_test.sh configs/deeplabv3plus/deeplabv3plus_r101-d8_480x480_60k_pascal_person_part_hiera_triplet.py deeplabv3plus_r101-d8_480x480_60k_pascal_person_part_hiera_triplet.pth 4 --aug-test --eval mIoU

shows very poor results as belows:

![multi](https://user-images.githubusercontent.com/66418958/204699810-e9abc4b8-a474-4eb3-ab9e-5d64796f7f07.png)


Is there something wrong?

**Comment by qhanghu** [comment]
Hi, 
thank you for your interest in this work.
We have update the implementation, you can pull the latest code and try it again.
BTW, for ms + flip testing, you should uncomment L24 and set `flip` in L25 to `True`.
https://github.com/qhanghu/HSSN_pytorch/blob/8b9c9db5f6b1f39a81e3167c039471cf6752b28a/configs/_base_/datasets/pascal_person_part.py#L24-L25
