### ISSUE TITLE
Use of Triplet loss for hierarchical segmentation

### ISSUE THREAD

**Issue by kulkarnikeerti** [qhanghu/HSSN_pytorch#3]
Hi @qhanghu thanks for the great work.

I was trying to use the loss for Mapillary dataset, but unfortunately I don't understand what these `hiera_map` and `hiera_index` indicates here? Can you please give me an example how this was created? I want to create the same for Mapillary dataset and use it. 

https://github.com/qhanghu/HSSN_pytorch/blob/c2386b758abda6dcfd86b572fe84b0527a6bc9e2/mmseg/models/losses/hiera_triplet_loss_cityscape.py#L10

Another question, do I have to change anything else other than this hierarchy in loss function to use it for Mapillary dataset?

Thanks in advance,
Keerti

**Comment by kulkarnikeerti** [comment]
I figured it out how its calculated here:)

**Comment by joshmyersdean** [comment]
Hi @kulkarnikeerti! 

Where did you find this calculation?

Thank you!
Josh

**Comment by kulkarnikeerti** [comment]
I didn't find it anywhere.I debugged the code to understand how its written.
If you follow the code, `hiera_map` is based on the `hiera` dictionary. First two elements in `hiera_map` are `0's` because the `flat` class contains two other elements in it (0 to 2 excluding 2). Similarly next three items are `1` as `construction` contains three elements in it (2 to 5 excluding 5) and so on...

**Comment by joshmyersdean** [comment]
Thank you @kulkarnikeerti! Have you found out how they're actually computing mIoU w.r.t. to the hierarchy?

**Comment by kulkarnikeerti** [comment]
I did not find the hierarchical loss for the mapillary dataset, but you can refer this and implement your own loss
https://github.com/qhanghu/HSSN_pytorch/blob/c2386b758abda6dcfd86b572fe84b0527a6bc9e2/mmseg/models/losses/hiera_loss.py#L122
