### ISSUE TITLE
Value of norm_config?

### ISSUE THREAD

**Issue by kulkarnikeerti** [qhanghu/HSSN_pytorch#4]
Hi @qhanghu ,

What does the `norm_config` indicates here? and what is the value of it? I don't see any parameter coming with this name nor I see default value. Could you please tell me what is this and its value?

https://github.com/qhanghu/HSSN_pytorch/blob/c2386b758abda6dcfd86b572fe84b0527a6bc9e2/mmseg/models/decode_heads/fcn_contrast_head.py#L89

**Comment by lingorX** [comment]
this setup extends the base_decode_head [here], please refer to mmseg for details.(https://github.com/qhanghu/HSSN_pytorch/blob/c2386b758abda6dcfd86b572fe84b0527a6bc9e2/mmseg/models/decode_heads/decode_head.py#L53)

**Comment by kulkarnikeerti** [comment]
Okay. Thanks
