### ISSUE TITLE
Focal loss calculation

### ISSUE THREAD

**Issue by kulkarnikeerti** [qhanghu/HSSN_pytorch#6]
Hi @qhanghu here I am again with one more doubt.

1. If I understand correctly `MCMA`, `MBMB`, `MALB` and `MCLA` computes the two constraints stated in the original paper? Is my understanding correct? 
2. Can you also tell me what does `MCMA`, `MCMB` .... stands for? (for better understanding)
3. Finally when calculating the loss you divide the loss by `num_valid` and also `num_classes`, but I don't see that part in the paper. why is it done? What will happen if we skip it?
 https://github.com/qhanghu/HSSN_pytorch/blob/c2386b758abda6dcfd86b572fe84b0527a6bc9e2/mmseg/models/losses/hiera_triplet_loss_cityscape.py#L104

Eagerly waiting for your response. Thanks:)

**Comment by lingorX** [comment]
Dividing the final value by num_valid*num_classes is equal to the mean reduction in CE/BCE/Focal losses.

**Comment by kulkarnikeerti** [comment]
Thanks @lingorX .
Is it `num_valid*num_classes` or `num_valid / num_clases`? Because in code I see division instead of multiplication

Could you also let me know what `MCMA`, `MCMB`, `MCLA`, `MCLB` stands for? I find it hard to relate with the equation in the paper. If you can tell me what they mean I can figure out the rest.

**Comment by lingorX** [comment]
Hi, 

sorry for the confusion, the suffix A stands for the most fine-grained classes (hierarchical level A) and B is the superclasses of the leaf nodes (hierarchical level B), respectively.

In addition, MCM corresponds to 
<img width="57" alt="image" src="https://user-images.githubusercontent.com/31980417/201491008-c9989fd7-caa1-4ff7-8bb7-aa979f9e3f3f.png">
 while MCL refers to 
<img width="60" alt="image" src="https://user-images.githubusercontent.com/31980417/201491057-f810ad6d-8632-4516-ae59-13d4ede8743b.png">
, in Eq. 6 of the paper.

**Comment by kulkarnikeerti** [comment]
@lingorX Thanks a lot for the explanation.
