### ISSUE TITLE
Ignoring some of the classes

### ISSUE THREAD

**Issue by kulkarnikeerti** [qhanghu/HSSN_pytorch#8]
Hi @qhanghu 

`num_valid` is used in the loss calculation, does this helps in ignoring the indices with 255 values? Does this acts as similar to `ignore_index` in Crossentropyloss? How exactly we ignore the labels with 255 in this code? 

https://github.com/qhanghu/HSSN_pytorch/blob/c2386b758abda6dcfd86b572fe84b0527a6bc9e2/mmseg/models/losses/hiera_triplet_loss_cityscape.py#L62

You assign id `0` to the labels with `255`, but there already exists a valid label with `0` id. In that case wouldn't it affect the original class when we assign `0` to the new class? Thanks

**Comment by lingorX** [comment]
"In that case wouldn't it affect the original class when we assign 0 to the new class"
No, it wouldn't.

Please note that finally, we multiply the loss with a valid index matrix (valid_indices in [here](https://github.com/qhanghu/HSSN_pytorch/blob/c2386b758abda6dcfd86b572fe84b0527a6bc9e2/mmseg/models/losses/hiera_triplet_loss_cityscape.py#L104) ) to set the loss of invalid pixels (label==255) to zero.

**Comment by kulkarnikeerti** [comment]
Thanks, understood:)
